steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'docker/Dockerfile.beacon'
      - '-t'
      - '${_IMAGE}'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_IMAGE}'

images:
  - '${_IMAGE}'

substitutions:
  _IMAGE: 'europe-north1-docker.pkg.dev/engrammic/engrammic/engrammic-beacon:latest'

options:
  logging: CLOUD_LOGGING_ONLY
