steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE}:latest'
      - '-t'
      - '${_IMAGE}:${SHORT_SHA}'
      - '-f'
      - 'docker/Dockerfile.dagster'
      - '.'
images:
  - '${_IMAGE}:latest'
  - '${_IMAGE}:${SHORT_SHA}'
substitutions:
  _IMAGE: 'europe-north1-docker.pkg.dev/engrammic/engrammic/engrammic-dagster'
options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: 'projects/engrammic/serviceAccounts/cloudbuild-dev@engrammic.iam.gserviceaccount.com'
