services:
  app:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 512M
    restart: always

  memgraph:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 2G
    command: ["--log-level=WARNING", "--query-execution-timeout-sec=30"]
    restart: always

  qdrant:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 1G
    restart: always

  redis:
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --maxmemory
      - 200mb
      - --maxmemory-policy
      - allkeys-lru
      - --save
      - "60"
      - "1000"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 256M
    restart: always

