steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--destination=${_IMAGE}:latest'
      - '--destination=${_IMAGE}:${SHORT_SHA}'
      - '--dockerfile=docker/Dockerfile.beacon'
      - '--context=.'
      - '--cache=true'
      - '--cache-repo=${_IMAGE}/cache'
      - '--cache-ttl=168h'
      - '--snapshot-mode=redo'
      - '--use-new-run'

substitutions:
  _IMAGE: 'europe-north1-docker.pkg.dev/engrammic/engrammic/engrammic-beacon'

options:
  logging: CLOUD_LOGGING_ONLY
