steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--destination=${_IMAGE}:latest'
      - '--destination=${_IMAGE}:${SHORT_SHA}'
      - '--dockerfile=docker/Dockerfile.dagster'
      - '--context=.'
      - '--cache=true'
      - '--cache-repo=${_IMAGE}/cache'
      - '--cache-ttl=168h'
      - '--snapshot-mode=redo'
      - '--use-new-run'

substitutions:
  _IMAGE: 'europe-north1-docker.pkg.dev/engrammic/engrammic/engrammic-dagster'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHMEM_8'

serviceAccount: 'projects/engrammic/serviceAccounts/cloudbuild-dev@engrammic.iam.gserviceaccount.com'
