"""Telemetry metrics - re-exports from recorder.py for backwards compatibility.

All functions are now backed by an in-process MetricsBuffer that flushes
to PostgreSQL, replacing the previous OTEL-based implementation.
"""

from __future__ import annotations

from context_service.telemetry.recorder import (
    ORPHAN_CHAINS_EXHAUSTED,
    ORPHAN_CHAINS_RECOVERED,
    get_buffer,
    get_db_pool,
    record_belief_confidence,
    record_cache_eviction,
    record_cache_hit,
    record_cache_miss,
    record_chain_evidence_modified,
    record_chain_feedback,
    record_chain_lookup,
    record_circuit_breaker_closed,
    record_circuit_breaker_opened,
    record_context_recall_size,
    record_db_query,
    record_embedding,
    record_embedding_cache_hit,
    record_embedding_cache_miss,
    record_engagement_latency,
    record_hard_query_detection,
    record_llm_call,
    record_llm_tokens,
    record_mcp_tool,
    record_node_confidence,
    record_orphan_chain_exhausted,
    record_orphan_chain_recovered,
    record_query_expansion,
    record_recall_depth,
    record_recall_latency,
    record_recall_result_count,
    record_request,
    record_reranking,
    record_source_tier_resolved,
    record_store_error,
    record_supersession_skipped,
    record_supersession_used,
    record_tool_error,
    set_db_pool,
    setup_metrics,
    track_active_request,
)

__all__ = [
    "ORPHAN_CHAINS_EXHAUSTED",
    "ORPHAN_CHAINS_RECOVERED",
    "get_buffer",
    "get_db_pool",
    "record_belief_confidence",
    "record_cache_eviction",
    "record_cache_hit",
    "record_cache_miss",
    "record_chain_evidence_modified",
    "record_chain_feedback",
    "record_chain_lookup",
    "record_circuit_breaker_closed",
    "record_circuit_breaker_opened",
    "record_context_recall_size",
    "record_db_query",
    "record_embedding",
    "record_embedding_cache_hit",
    "record_embedding_cache_miss",
    "record_engagement_latency",
    "record_hard_query_detection",
    "record_llm_call",
    "record_llm_tokens",
    "record_mcp_tool",
    "record_node_confidence",
    "record_orphan_chain_exhausted",
    "record_orphan_chain_recovered",
    "record_query_expansion",
    "record_recall_depth",
    "record_recall_latency",
    "record_recall_result_count",
    "record_reranking",
    "record_request",
    "record_source_tier_resolved",
    "record_store_error",
    "record_supersession_skipped",
    "record_supersession_used",
    "record_tool_error",
    "set_db_pool",
    "setup_metrics",
    "track_active_request",
]
