"""Multi-chain session management (v1.4 Phase 4c).

A :ReasoningSession groups one or more :ReasoningChain nodes produced during a
single agent interaction window.  Chains are linked to the session via
:PART_OF_SESSION edges.  When a session is closed, cross-chain :REFERENCES
edges are created so the provenance graph captures intra-session reasoning
dependencies.

Public API
----------
create_or_join_session(store, session_id, silo_id) -> str
    Upsert a :ReasoningSession node and return its id.

attach_chain_to_session(store, chain_id, session_id, silo_id) -> None
    Link a :ReasoningChain to a :ReasoningSession.

close_session(store, session_id, silo_id) -> int
    Close a session and return the number of cross-chain REFERENCES edges created.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import TYPE_CHECKING

import structlog

from context_service.db.queries import (
    ATTACH_CHAIN_TO_SESSION,
    CLOSE_REASONING_SESSION,
    CREATE_CROSS_CHAIN_REFERENCES,
    CREATE_REASONING_SESSION,
    GET_SESSION_CHAINS,
    GET_SESSION_STATUS,
)

if TYPE_CHECKING:
    from context_service.engine.protocols import HyperGraphStore

logger = structlog.get_logger(__name__)


def _now_iso() -> str:
    return datetime.now(UTC).isoformat()


async def create_or_join_session(
    store: HyperGraphStore,
    session_id: str,
    silo_id: str,
) -> str:
    """Upsert a :ReasoningSession node and return its id.

    If a session with the given id already exists and is still open, it is
    returned as-is (with updated_at refreshed).  If it is already closed a
    new session id should be generated by the caller.

    Parameters
    ----------
    store:
        HyperGraphStore implementation.
    session_id:
        Caller-supplied session identifier (UUID string).
    silo_id:
        Owning silo.

    Returns
    -------
    str
        The session_id (unchanged from input).
    """
    # Guard: refuse to re-join a closed session.
    existing = await store.execute_query(
        GET_SESSION_STATUS,
        {"session_id": session_id, "silo_id": silo_id},
    )
    if existing and existing[0].get("status") == "closed":
        raise ValueError(
            f"ReasoningSession {session_id!r} is already closed; "
            "generate a new session_id to start a fresh session."
        )

    now = _now_iso()
    await store.execute_write(
        CREATE_REASONING_SESSION,
        {"session_id": session_id, "silo_id": silo_id, "created_at": now},
    )
    logger.debug("session_upserted", session_id=session_id, silo_id=silo_id)
    return session_id


async def attach_chain_to_session(
    store: HyperGraphStore,
    chain_id: str,
    session_id: str,
    silo_id: str,
) -> None:
    """Link a :ReasoningChain to a :ReasoningSession via :PART_OF_SESSION.

    Parameters
    ----------
    store:
        HyperGraphStore implementation.
    chain_id:
        ID of the :ReasoningChain node to attach.
    session_id:
        ID of the target :ReasoningSession.
    silo_id:
        Owning silo.
    """
    now = _now_iso()
    await store.execute_write(
        ATTACH_CHAIN_TO_SESSION,
        {"chain_id": chain_id, "session_id": session_id, "silo_id": silo_id, "created_at": now},
    )
    logger.debug(
        "chain_attached_to_session",
        chain_id=chain_id,
        session_id=session_id,
        silo_id=silo_id,
    )


async def close_session(
    store: HyperGraphStore,
    session_id: str,
    silo_id: str,
) -> int:
    """Close a :ReasoningSession and wire cross-chain :REFERENCES edges.

    Steps:
    1. Fetch all chains attached to the session.
    2. Create directed :REFERENCES edges between chains (oldest -> newest).
    3. Mark the session as closed.

    Parameters
    ----------
    store:
        HyperGraphStore implementation.
    session_id:
        ID of the session to close.
    silo_id:
        Owning silo.

    Returns
    -------
    int
        Number of :REFERENCES edges created.
    """
    chains = await store.execute_query(
        GET_SESSION_CHAINS,
        {"session_id": session_id, "silo_id": silo_id},
    )
    chain_count = len(chains)

    now = _now_iso()
    edges_created = 0
    if chain_count > 1:
        rows = await store.execute_write(
            CREATE_CROSS_CHAIN_REFERENCES,
            {"session_id": session_id, "silo_id": silo_id, "created_at": now},
        )
        if rows:
            edges_created = int(rows[0].get("edges_created", 0))

    await store.execute_write(
        CLOSE_REASONING_SESSION,
        {"session_id": session_id, "silo_id": silo_id, "closed_at": now},
    )

    logger.info(
        "session_closed",
        session_id=session_id,
        silo_id=silo_id,
        chain_count=chain_count,
        cross_chain_edges=edges_created,
    )
    return edges_created
