"""Ingest data: plans/ — project decisions, EAG gaps, and phase status."""
from __future__ import annotations
from typing import Any

ITEMS: list[dict[str, Any]] = [
    {
        "content": "v1d Signals Enhancement shipped: heat ranking, unified decay, and write events.",
        "layer": "memory",
        "tags": ["phases", "status"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "v1.5 Agent Identity shipped: agent nodes, reflection filtering, chain continuity, and per-silo config.",
        "layer": "memory",
        "tags": ["phases", "status"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "v1.4.1 MCP QoL is complete and archived.",
        "layer": "memory",
        "tags": ["phases", "status"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "v1.3, v1.2, and v1.1 EAG completion plans are archived.",
        "layer": "memory",
        "tags": ["phases", "status"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "v1-beta production hardening and v1-alpha paradigm gaps plans are archived.",
        "layer": "memory",
        "tags": ["phases", "status"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "No plans are currently active as of 2026-05-04. Next candidates are OSS launch prep and clustering algorithm evaluation.",
        "layer": "memory",
        "tags": ["phases", "status"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "The EAG integration audit was produced on 2026-04-26 during the port of ~150 files from the prototype repo (NovusEdge/CTXR) into context-service.",
        "layer": "memory",
        "tags": ["phases", "status"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "phase-eag-b-edge-migration closed EAG audit TODOs #1 and #2 on 2026-04-28.",
        "layer": "memory",
        "tags": ["phases", "status"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "Prompts README TODO (audit item #1) closed 2026-05-03: README added at config/prompts/custodian/README.md.",
        "layer": "memory",
        "tags": ["phases", "status"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "RelationshipType.CAUSES alignment resolved 2026-04-29: extraction vocabulary enum and CITEEdgeType are intentionally separate. See context/architecture/enum-registries.md.",
        "layer": "memory",
        "tags": ["phases", "status"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "All EAG integration audit open questions are resolved as of 2026-05-01.",
        "layer": "memory",
        "tags": ["phases", "status"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "E2E test scenarios plan is in Draft status as of 2026-05-01. Four scenarios are defined: provenance chain integrity, reflection round-trip, recall quality, MCP protocol validation.",
        "layer": "memory",
        "tags": ["testing", "e2e"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "E2E scenario 1 (provenance chain integrity) tests that after ingest and extraction, context_provenance returns chains including the source document via REFERENCES edge traversal.",
        "layer": "memory",
        "tags": ["testing", "e2e"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "E2E scenario 2 (reflection round-trip) tests that MetaObservations stored via context_reflect are retrievable via context_get_reflections with correct observation_type and agent_id.",
        "layer": "memory",
        "tags": ["testing", "e2e"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "E2E scenario 3 (recall quality) seeds a corpus of 5-10 documents and asserts Precision@3 per query, that relevant docs rank above irrelevant, and that freshness affects ranking.",
        "layer": "memory",
        "tags": ["testing", "e2e"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "E2E scenario 4 (MCP protocol validation) sends JSON-RPC tool calls to a live FastMCP server instance and asserts MCP-spec response structure, correct error codes, and auth context propagation.",
        "layer": "memory",
        "tags": ["testing", "e2e"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "Clustering algorithm evaluation is a spike in progress on branch phase-clustering-algo-eval. No production changes until a decision is made.",
        "layer": "memory",
        "tags": ["phases", "status"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "RAG-era :Finding label and EAG :Fact label were mismatched: Finding is the custodian synthesis output, Fact is the EAG Knowledge layer promoted node. The db/indexes.py :Fact index had no write path.",
        "layer": "knowledge",
        "tags": ["eag", "schema", "known-issue"],
        "evidence": ["doc:eag-integration-audit.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "Finding vs Fact label mismatch resolved 2026-04-28 by phase-eag-a-claim-fact-promotion: Claim->Fact write path creates separate :Fact nodes with PROMOTED_FROM edges. See context/architecture/README.md.",
        "layer": "knowledge",
        "tags": ["eag", "schema", "known-issue"],
        "evidence": ["doc:eag-integration-audit.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "primitives.eag.epistemology.promotion (should_promote_r1, should_promote_r2, ClaimForPromotion, PromotionDecision) was not used in context-service at port time. The custodian's promotion.py implemented Finding-level draft->published status flips, not Claim->Fact promotion.",
        "layer": "knowledge",
        "tags": ["eag", "primitives", "gaps"],
        "evidence": ["doc:eag-integration-audit.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "primitives.eag.epistemology.supersession (should_supersede, detect_contradiction) was not used in context-service at port time. custodian/supersession.py uses LLM calls for free-text nodes; primitives target structured :Claim/:Fact comparison.",
        "layer": "knowledge",
        "tags": ["eag", "primitives", "gaps"],
        "evidence": ["doc:eag-integration-audit.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "primitives.eag.epistemology.confidence was not used in context-service at port time.",
        "layer": "knowledge",
        "tags": ["eag", "primitives", "gaps"],
        "evidence": ["doc:eag-integration-audit.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "primitives epistemology integration gaps are not bugs: the primitives target a structured :Claim/:Fact graph that had no write path at port time. They become relevant once EAG Claim->Fact promotion is implemented.",
        "layer": "knowledge",
        "tags": ["eag", "primitives", "gaps"],
        "evidence": ["doc:eag-integration-audit.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "evaluate_claim_for_fact() adapter in custodian/fact_promotion.py wraps should_promote_r1 and should_promote_r2 from primitives. Claim->Fact promotion resolved 2026-05-01.",
        "layer": "knowledge",
        "tags": ["eag", "primitives", "gaps"],
        "evidence": ["doc:eag-integration-audit.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "extraction/models.py:RelationshipType.CAUSES duplicates CITEEdgeType.CAUSES as a local enum value. Decision: keep them separate because they serve different purposes (LLM extraction vocabulary vs graph edge type registry).",
        "layer": "knowledge",
        "tags": ["eag", "gaps", "technical-debt"],
        "evidence": ["doc:eag-integration-audit.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "CITEEdgeType.CAUSES and CITEEdgeType.CORROBORATES are defined in primitives but have no write path in context-service.",
        "layer": "knowledge",
        "tags": ["eag", "gaps", "technical-debt"],
        "evidence": ["doc:eag-integration-audit.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "EDGE_REFERENCES remains a plain string in db/schema.py because it is not yet in CITEEdgeType. This is intentional and documented.",
        "layer": "knowledge",
        "tags": ["eag", "gaps", "technical-debt"],
        "evidence": ["doc:eag-integration-audit.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "Layer transition wiring T1-T9 has no explicit wiring code in context-service. T3 (Claim:Commitment -> Finding) is implemented via consensus_promotion.py; T1, T2, T4 are Dagster asset pipelines. This is architecturally consistent.",
        "layer": "knowledge",
        "tags": ["eag", "gaps", "technical-debt"],
        "evidence": ["doc:eag-integration-audit.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "Two prompt-loading mechanisms exist intentionally: custodian uses YAML lens composition (config/prompts/custodian/), extraction and clustering use provider-preset switching via config_loader. They are not candidates for unification.",
        "layer": "wisdom",
        "tags": ["architecture", "decisions"],
        "evidence": [],
        "about": ["custodian/prompt_loader.py", "config/config_loader.py"],
        "steps": None,
    },
    {
        "content": "Leiden clustering runs via igraph workaround because MAGE native leiden_community_detection.get raises 'No communities detected' at all resolutions. Batched daily off-peak because Leiden is too slow for incremental post-write runs.",
        "layer": "wisdom",
        "tags": ["architecture", "decisions"],
        "evidence": [],
        "about": ["clustering/service.py"],
        "steps": None,
    },
    {
        "content": "LPA (Label Propagation) is the preferred Leiden replacement candidate: O(n+m) complexity, MAGE-native, no igraph dependency, could run incrementally after each custodian sweep instead of daily. Main risk is non-determinism on sparse graphs.",
        "layer": "wisdom",
        "tags": ["architecture", "decisions"],
        "evidence": [],
        "about": ["clustering/service.py"],
        "steps": None,
    },
    {
        "content": "HDBSCAN as a clustering replacement loses relational structure: semantically similar but graph-disconnected nodes (e.g., contradicting facts from different sources) could land in the same cluster. Only viable as a first-pass with graph connectivity validation.",
        "layer": "wisdom",
        "tags": ["architecture", "decisions"],
        "evidence": [],
        "about": ["clustering/service.py"],
        "steps": None,
    },
    {
        "content": "Louvain is worth benchmarking against Leiden before adopting LPA: it is MAGE-native, faster in practice, and lowest-risk swap if quality is within range. Weaker theoretical guarantees than Leiden (can produce disconnected communities).",
        "layer": "wisdom",
        "tags": ["architecture", "decisions"],
        "evidence": [],
        "about": ["clustering/service.py"],
        "steps": None,
    },
    {
        "content": "OSS launch timing decision: lean toward launching after Silt design partner traction. Revisit after partner talks progress.",
        "layer": "wisdom",
        "tags": ["oss", "strategy"],
        "evidence": [],
        "about": ["context/plans/oss-master.md"],
        "steps": None,
    },
    {
        "content": "OSS scope: open-source primitives and a single-tenant SQLite-backed engine repo (delta-prime/engine/). The production context-service remains closed.",
        "layer": "wisdom",
        "tags": ["oss", "strategy"],
        "evidence": [],
        "about": ["context/plans/oss-master.md"],
        "steps": None,
    },
    {
        "content": "OSS engine repo (W1) and manifesto (W2) are parallel workstreams. Launch prep (W3) depends on both being mostly complete.",
        "layer": "wisdom",
        "tags": ["oss", "strategy"],
        "evidence": [],
        "about": ["context/plans/oss-master.md"],
        "steps": None,
    },
    {
        "content": "OSS engine repo is licensed Apache 2.0. Structure mirrors context-service with store/ and mcp/ under src/engine/.",
        "layer": "wisdom",
        "tags": ["oss", "strategy"],
        "evidence": [],
        "about": ["context/plans/oss-engine.md"],
        "steps": None,
    },
    {
        "content": "New code in context-service must depend on engine/protocols.py interfaces, not on memgraph_store or qdrant_store directly.",
        "layer": "wisdom",
        "tags": ["architecture", "decisions"],
        "evidence": [],
        "about": ["engine/protocols.py"],
        "steps": None,
    },
    {
        "content": "Clustering evaluation recommended order: (1) benchmark Louvain vs Leiden, (2) spike LPA stability across 10 runs, (3) spike HDBSCAN hybrid only if LPA stability is unacceptable.",
        "layer": "intelligence",
        "tags": ["architecture", "decisions"],
        "evidence": [],
        "about": [],
        "steps": [
            {"step": 1, "reasoning": "Benchmark Louvain vs Leiden on a sample silo. Accept Louvain if quality is within range — lowest-risk change.", "confidence": 0.8},
            {"step": 2, "reasoning": "Spike LPA: run 10 times on the same sample silo and compare community assignments for stability.", "confidence": 0.75},
            {"step": 3, "reasoning": "If LPA stability is unacceptable, spike HDBSCAN as a hybrid: embed-space candidate clusters + graph connectivity rejection pass.", "confidence": 0.7},
        ],
    },
]
