"""Ingest data: CLAUDE.md — project architecture, rules, and conventions."""

from __future__ import annotations

from typing import Any

ITEMS: list[dict[str, Any]] = [
    {
        "content": "context-service is the Delta Prime production backend, ported 2026-04-26 from the NovusEdge/CTXR prototype.",
        "layer": "memory",
        "tags": ["stack", "infrastructure"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "context-service lives in the delta-prime/ monorepo alongside primitives/ (open-source library) at ../primitives.",
        "layer": "memory",
        "tags": ["stack", "infrastructure"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "primitives is wired into context-service as an editable path source via [tool.uv.sources] in pyproject.toml.",
        "layer": "memory",
        "tags": ["stack", "infrastructure"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "The service runtime stack is: Python 3.12+, FastAPI, FastMCP, Memgraph (via neo4j driver), Qdrant, Redis, Dagster, structlog.",
        "layer": "memory",
        "tags": ["stack", "infrastructure"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "Optional stack extras: Vertex AI, Gemini, Anthropic, OpenAI (extras: llm, embeddings), WorkOS (extra: auth).",
        "layer": "memory",
        "tags": ["stack", "infrastructure"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "The service exposes two surfaces: MCP server (primary agent interface) and FastAPI REST (admin/dashboard). No SDK.",
        "layer": "memory",
        "tags": ["stack", "infrastructure"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "All Python invocations must go through `uv run`. Never use the system Python directly.",
        "layer": "memory",
        "tags": ["commands", "dev"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "`just install-dev` runs `uv sync --all-extras` to install all dependencies including optional extras.",
        "layer": "memory",
        "tags": ["commands", "dev"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "`just lint` runs `ruff check src tests`; `just typecheck` runs `mypy src` in strict mode; `just check` runs both.",
        "layer": "memory",
        "tags": ["commands", "dev"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "`just format` runs `ruff format` followed by `ruff check --fix`.",
        "layer": "memory",
        "tags": ["commands", "dev"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "`just test` runs pytest with asyncio_mode = auto; `just test-integration` runs pytest -m integration -v and requires a live docker stack.",
        "layer": "memory",
        "tags": ["commands", "dev"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "`just dev` starts FastAPI with RELOAD=true; `just run` starts FastAPI without reload via python -m context_service.",
        "layer": "memory",
        "tags": ["commands", "dev"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "`just dagster-web` starts the Dagster webserver on port 3000 for the context_service.pipelines module.",
        "layer": "memory",
        "tags": ["commands", "dev"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "Docker commands (`just docker-up`, `docker-down`, etc.) must not be run without asking the user first.",
        "layer": "memory",
        "tags": ["commands", "dev"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "EAG stands for Epistemic Augmented Generation — the generation process describing how agents use the system.",
        "layer": "memory",
        "tags": ["naming", "paradigm"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "CITE stands for Context In Tiered Epistemology — the architecture and schema (e.g., CITEEdgeType in primitives).",
        "layer": "memory",
        "tags": ["naming", "paradigm"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "Meta-Memory is cross-cutting observability (provenance, time-travel, reflection). It is not a fifth cognitive layer.",
        "layer": "memory",
        "tags": ["naming", "paradigm"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "The four cognitive layers are: Memory, Knowledge, Wisdom, Intelligence — in that order of promotion.",
        "layer": "memory",
        "tags": ["naming", "paradigm"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "EAG is the production successor to the prototype's CAG (Context Augmented Generation) paradigm.",
        "layer": "memory",
        "tags": ["naming", "paradigm"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "api/ contains the FastAPI app factory (api/app.py, called via __main__.py), routes, and dependency wiring (deps.py).",
        "layer": "knowledge",
        "tags": ["architecture", "api"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "mcp/ contains the MCP server (server.py) and tool implementations under mcp/tools/. This is the primary agent surface.",
        "layer": "knowledge",
        "tags": ["architecture", "mcp"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "engine/ contains storage protocols and concrete adapters: memgraph_store.py, qdrant_store.py, models.py, protocols.py, queries.py.",
        "layer": "knowledge",
        "tags": ["architecture", "engine"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "stores/ contains lower-level connection clients for Memgraph, Qdrant, and Redis, used by engine/ and elsewhere.",
        "layer": "knowledge",
        "tags": ["architecture", "stores"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "db/ contains Cypher query bundles and index/schema management: indexes.py, schema.py, queries.py, custodian_queries.py, custodian_read_queries.py.",
        "layer": "knowledge",
        "tags": ["architecture", "db"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "extraction/ implements the claim extraction pipeline: service.py, identity.py, alias_lookup.py, prompts.py, and a multi-stage filter/ (rules, wikidata, llm_classifier, orchestrator, circuit_breaker, audit).",
        "layer": "knowledge",
        "tags": ["architecture", "extraction"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "clustering/ implements Leiden clustering and hierarchical summaries via service.py, queries.py, prompts.py, job_store.py.",
        "layer": "knowledge",
        "tags": ["architecture", "clustering"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "custodian/ is the largest subsystem. Workers visit nodes, validate claims, and promote :Claim to :Fact via R1/R2 consensus. Key files: dispatch.py, visit.py, consensus_promotion.py, supersession.py, validators.py, business_rules.py, handlers/, sensors/.",
        "layer": "knowledge",
        "tags": ["architecture", "custodian"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "pipelines/ contains Dagster definitions.py, resources.py, assets/, sensors/. Current DAG direction is Option B: parallel embed+extract, partitioned by silo_id.",
        "layer": "knowledge",
        "tags": ["architecture", "pipelines"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "signals/ implements heat, freshness, and priority scoring (proprietary; ported from prototype).",
        "layer": "knowledge",
        "tags": ["architecture", "signals"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "embeddings/ contains Jina and Vertex clients with base.py as the protocol. SPLADE is referenced in plans but not yet wired.",
        "layer": "knowledge",
        "tags": ["architecture", "embeddings"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "llm/ contains Anthropic, OpenAI, Gemini, and Vertex Gemini clients behind a base.py protocol.",
        "layer": "knowledge",
        "tags": ["architecture", "llm"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "cache/ provides Redis-backed embedding, lookup, and node caches.",
        "layer": "knowledge",
        "tags": ["architecture", "cache"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "services/ contains higher-level orchestration glue: context.py and silo.py.",
        "layer": "knowledge",
        "tags": ["architecture", "services"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "config/ contains settings.py (pydantic-settings), config_loader.py, and logging.py (structlog).",
        "layer": "knowledge",
        "tags": ["architecture", "config"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "core/ contains service_factory.py, trace_context.py, and an additional settings.py.",
        "layer": "knowledge",
        "tags": ["architecture", "core"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "models/ contains cross-cutting Pydantic models including inference.py.",
        "layer": "knowledge",
        "tags": ["architecture", "models"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "The multi-tenancy boundary throughout the service is silo_id. Every store, lookup, and MCP tool takes a silo and is partitioned by it.",
        "layer": "knowledge",
        "tags": ["architecture", "multi-tenancy"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "MCP read tools: context_get, context_query, context_graph, context_history, context_provenance.",
        "layer": "knowledge",
        "tags": ["mcp", "api"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "MCP write tools (one verb per layer): context_remember (Memory), context_assert (Knowledge, evidence-required), context_commit (Wisdom), context_reason (Intelligence, multi-step chains), context_reflect (meta-memory).",
        "layer": "knowledge",
        "tags": ["mcp", "api"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "MCP linking tool: context_link. MCP tenancy tools: silo_create, silo_list.",
        "layer": "knowledge",
        "tags": ["mcp", "api"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_get (cached) performance target: < 20ms.",
        "layer": "knowledge",
        "tags": ["performance", "slo"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_query performance target: < 250ms.",
        "layer": "knowledge",
        "tags": ["performance", "slo"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "Single-layer writes (context_remember, context_assert, context_commit, context_reflect) performance target: < 300ms p95.",
        "layer": "knowledge",
        "tags": ["performance", "slo"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_graph (depth 2) performance target: < 500ms.",
        "layer": "knowledge",
        "tags": ["performance", "slo"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_reason (chained) performance target: < 400ms p95.",
        "layer": "knowledge",
        "tags": ["performance", "slo"],
        "evidence": ["doc:CLAUDE.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "For new paradigm work, read ../primitives/context/specs/ (EAG). For shipped or legacy code paths, read ../primitives/context/specs/rag/.",
        "layer": "wisdom",
        "tags": ["rules", "standards"],
        "evidence": [],
        "about": ["context-service", "primitives"],
        "steps": None,
    },
    {
        "content": "Check context/plans/ before starting non-trivial work — there may already be an active plan covering the area.",
        "layer": "wisdom",
        "tags": ["rules", "standards"],
        "evidence": [],
        "about": ["context-service"],
        "steps": None,
    },
    {
        "content": "Never commit directly to main. Use phase branches following the phase-N/description or phase-eag-<letter>-<desc> conventions.",
        "layer": "wisdom",
        "tags": ["rules", "standards"],
        "evidence": [],
        "about": ["context-service"],
        "steps": None,
    },
    {
        "content": "No emojis in code or documentation.",
        "layer": "wisdom",
        "tags": ["rules", "standards"],
        "evidence": [],
        "about": ["context-service"],
        "steps": None,
    },
    {
        "content": "mypy runs in strict mode and ruff selects E,F,I,UP,B,SIM,ARG. Both must pass before merging — run `just check`.",
        "layer": "wisdom",
        "tags": ["rules", "standards"],
        "evidence": [],
        "about": ["context-service"],
        "steps": None,
    },
    {
        "content": ":Finding reads must filter WHERE r.source = 'extraction' OR r.status = 'published' unless drafts are explicitly requested.",
        "layer": "wisdom",
        "tags": ["rules", "standards"],
        "evidence": [],
        "about": ["context-service"],
        "steps": None,
    },
    {
        "content": "New code must depend on engine/protocols.py interfaces, not on memgraph_store or qdrant_store directly.",
        "layer": "wisdom",
        "tags": ["rules", "standards"],
        "evidence": [],
        "about": ["context-service", "engine"],
        "steps": None,
    },
    {
        "content": "primitives is wired as an editable path source — changes there land immediately. Coordinate when modifying both repos simultaneously.",
        "layer": "wisdom",
        "tags": ["rules", "standards"],
        "evidence": [],
        "about": ["context-service", "primitives"],
        "steps": None,
    },
    {
        "content": "Primitives imports use primitives.eag.* (epistemology, agents) and primitives.schema.* (CITEEdgeType, labels). The old primitives.cag path no longer exists.",
        "layer": "wisdom",
        "tags": ["rules", "standards"],
        "evidence": [],
        "about": ["context-service", "primitives"],
        "steps": None,
    },
]
