"""Ingest data: api-examples.md — MCP tool contracts and patterns."""

from __future__ import annotations

from typing import Any

ITEMS: list[dict[str, Any]] = [
    {
        "content": "context_store accepts params: content (str, required), layer (str, default 'memory'), evidence (str or list[str], null), about (list[str], null), steps (list[dict], null), tags (list[str], null), session (str, null).",
        "layer": "memory",
        "tags": ["api", "mcp", "contract", "context_store"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_store layer param accepts exactly: memory | knowledge | wisdom | intelligence | meta.",
        "layer": "memory",
        "tags": ["api", "mcp", "contract", "context_store"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_store: evidence is required for the knowledge layer; accepts node:<uuid> refs or URIs.",
        "layer": "memory",
        "tags": ["api", "mcp", "contract", "context_store", "knowledge"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_store: about is required for the wisdom and meta layers; value is a list of node IDs the entry concerns.",
        "layer": "memory",
        "tags": ["api", "mcp", "contract", "context_store", "wisdom", "meta"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_store: steps is required for the intelligence layer; each dict has keys step (int) and reasoning (str); confidence (float) is optional.",
        "layer": "memory",
        "tags": ["api", "mcp", "contract", "context_store", "intelligence"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_recall accepts params: query (str, null), mode (str, default 'search'), node_ids (list[str], null), depth (int, default 0), layers (list[str], null), top_k (int, default 10), as_of (str, null).",
        "layer": "memory",
        "tags": ["api", "mcp", "contract", "context_recall"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_recall mode param accepts exactly: search | fetch | graph | history | provenance.",
        "layer": "memory",
        "tags": ["api", "mcp", "contract", "context_recall"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_recall: query is required for search and graph modes; node_ids is required for fetch, history, and provenance modes.",
        "layer": "memory",
        "tags": ["api", "mcp", "contract", "context_recall"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_recall depth param range is 1-5; values > 0 trigger graph traversal; used with graph mode.",
        "layer": "memory",
        "tags": ["api", "mcp", "contract", "context_recall", "graph"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_link accepts params: from_id (str, required), to_id (str, required), rel (str, required), weight (float, default 1.0, range 0.0-10.0), note (str, null).",
        "layer": "memory",
        "tags": ["api", "mcp", "contract", "context_link"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_link rel param accepts exactly: supports | contradicts | derives | supersedes | references.",
        "layer": "memory",
        "tags": ["api", "mcp", "contract", "context_link"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "silo_id is not passed by MCP callers; it is derived from the authenticated session.",
        "layer": "memory",
        "tags": ["api", "mcp", "contract", "tenancy"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "MCP is the primary agent-facing interface; the REST API is used for admin, dashboard, and silo management only.",
        "layer": "memory",
        "tags": ["api", "mcp", "contract", "architecture"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "The three MCP tools are context_store (write to any layer), context_recall (read, search, traverse, trace), and context_link (create typed relationships).",
        "layer": "memory",
        "tags": ["api", "mcp", "contract"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "REST API base path is /api/v1. All requests require Authorization: Bearer {api_key}.",
        "layer": "memory",
        "tags": ["api", "rest", "contract", "auth"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_store memory layer response includes node_id, layer, and created_at.",
        "layer": "knowledge",
        "tags": ["api", "mcp", "contract", "context_store", "memory"],
        "evidence": ["doc:api-examples.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_store knowledge layer response includes node_id, layer, evidence_status, evidence_nodes, promoted_to_fact, and created_at.",
        "layer": "knowledge",
        "tags": ["api", "mcp", "contract", "context_store", "knowledge"],
        "evidence": ["doc:api-examples.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_store wisdom layer response includes node_id, layer, declared_by (agent UUID), about_nodes, and created_at.",
        "layer": "knowledge",
        "tags": ["api", "mcp", "contract", "context_store", "wisdom"],
        "evidence": ["doc:api-examples.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_store intelligence layer response includes chain_id, layer, steps_count, crystallizations_queued, session_id, and created_at. Crystallizations are extracted automatically as Knowledge candidates.",
        "layer": "knowledge",
        "tags": ["api", "mcp", "contract", "context_store", "intelligence"],
        "evidence": ["doc:api-examples.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_store meta layer response includes node_id, layer, about_nodes, and created_at.",
        "layer": "knowledge",
        "tags": ["api", "mcp", "contract", "context_store", "meta"],
        "evidence": ["doc:api-examples.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_recall search mode response includes results array (each with node_id, layer, content, summary, confidence, relevance_score, tags, created_at), total_candidates, and search_time_ms.",
        "layer": "knowledge",
        "tags": ["api", "mcp", "contract", "context_recall", "search"],
        "evidence": ["doc:api-examples.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_recall fetch mode response includes a nodes array; each node has node_id, content, type, layer, summary, confidence, tags, and created_at.",
        "layer": "knowledge",
        "tags": ["api", "mcp", "contract", "context_recall", "fetch"],
        "evidence": ["doc:api-examples.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_recall graph mode accepts either a semantic query string or explicit node_ids as seed. Response includes nodes, edges, and traversal_stats (depth_reached, nodes_visited, edges_traversed).",
        "layer": "knowledge",
        "tags": ["api", "mcp", "contract", "context_recall", "graph"],
        "evidence": ["doc:api-examples.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_recall history mode traverses the SUPERSEDES chain oldest-to-newest. Response timeline entries include node_id, content, valid_from, valid_to, confidence, supersession_reason. Response also includes current node ID and entries_count.",
        "layer": "knowledge",
        "tags": ["api", "mcp", "contract", "context_recall", "history"],
        "evidence": ["doc:api-examples.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_recall provenance mode traces citation chain back to Memory-layer sources by following DERIVED_FROM, PROMOTED_FROM, and SYNTHESIZED_FROM edges. Response includes node_id, chain, root_sources, and chain_length.",
        "layer": "knowledge",
        "tags": ["api", "mcp", "contract", "context_recall", "provenance"],
        "evidence": ["doc:api-examples.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_link response includes edge_id, from_id, to_id, rel, and created_at.",
        "layer": "knowledge",
        "tags": ["api", "mcp", "contract", "context_link"],
        "evidence": ["doc:api-examples.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "REST POST /api/v1/context/lookup accepts silo_id, query, filters (layer, tags, time_range with start/end ISO 8601), top_k, include_related, and max_depth.",
        "layer": "knowledge",
        "tags": ["api", "rest", "contract", "lookup"],
        "evidence": ["doc:api-examples.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "REST POST /api/v1/context store response: {node_id, status: 'created', extraction_queued: true}.",
        "layer": "knowledge",
        "tags": ["api", "rest", "contract", "store"],
        "evidence": ["doc:api-examples.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "REST DELETE /api/v1/nodes/{node_id} performs erasure cascade; response reports derived_nodes_nulled count and vector_deleted flag.",
        "layer": "knowledge",
        "tags": ["api", "rest", "contract", "delete", "erasure"],
        "evidence": ["doc:api-examples.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_recall fetch (cached) target latency: < 20ms.",
        "layer": "knowledge",
        "tags": ["performance", "slo"],
        "evidence": ["doc:api-examples.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_recall search target latency: < 250ms.",
        "layer": "knowledge",
        "tags": ["performance", "slo"],
        "evidence": ["doc:api-examples.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_store single-layer writes target latency: < 300ms p95.",
        "layer": "knowledge",
        "tags": ["performance", "slo"],
        "evidence": ["doc:api-examples.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_recall graph (depth 2) target latency: < 500ms.",
        "layer": "knowledge",
        "tags": ["performance", "slo"],
        "evidence": ["doc:api-examples.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "context_recall history and provenance target latency: < 400ms p95.",
        "layer": "knowledge",
        "tags": ["performance", "slo"],
        "evidence": ["doc:api-examples.md"],
        "about": [],
        "steps": None,
    },
    {
        "content": "error node_not_found: node may have been deleted or does not belong to the current silo.",
        "layer": "memory",
        "tags": ["api", "errors"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "error missing_required_param: returned with param name when a layer-specific required field is absent (e.g. evidence for knowledge layer).",
        "layer": "memory",
        "tags": ["api", "errors"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "error invalid_evidence: returned when the referenced evidence node does not exist in the silo.",
        "layer": "memory",
        "tags": ["api", "errors"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "error as_of_not_supported: point-in-time retrieval via the as_of param is not yet implemented.",
        "layer": "memory",
        "tags": ["api", "errors"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "error rate_limit_exceeded: includes retry_after (seconds) and quota object with limit, remaining, and reset_at.",
        "layer": "memory",
        "tags": ["api", "errors"],
        "evidence": [],
        "about": [],
        "steps": None,
    },
    {
        "content": "Pattern 1 (store then search): store an observation to the memory layer, capture the returned node_id, later use context_recall search to surface relevant nodes, then fetch full content by node_id for prompt injection.",
        "layer": "intelligence",
        "tags": ["api", "mcp", "pattern", "agent-integration"],
        "evidence": [],
        "about": [],
        "steps": [
            {
                "step": 1,
                "reasoning": "Call context_store with layer=memory to persist the observation; capture node_id from the response.",
                "confidence": 0.95,
            },
            {
                "step": 2,
                "reasoning": "Later, call context_recall with mode=search and the current query to surface semantically relevant nodes.",
                "confidence": 0.95,
            },
            {
                "step": 3,
                "reasoning": "For each top result, call context_recall with mode=fetch and the node_id to retrieve full content.",
                "confidence": 0.9,
            },
            {
                "step": 4,
                "reasoning": "Inject fetched content into the prompt context before generating a response.",
                "confidence": 0.9,
            },
        ],
    },
    {
        "content": "Pattern 2 (assert claim with evidence): store a knowledge-layer claim backed by a memory node by passing its ref as evidence in context_store using the node:<uuid> format.",
        "layer": "intelligence",
        "tags": ["api", "mcp", "pattern", "agent-integration", "knowledge"],
        "evidence": [],
        "about": [],
        "steps": [
            {
                "step": 1,
                "reasoning": "Identify the memory node that supports the claim; note its node_id.",
                "confidence": 0.95,
            },
            {
                "step": 2,
                "reasoning": "Call context_store with layer=knowledge, the claim as content, and evidence=[f'node:{node_id}'].",
                "confidence": 0.95,
            },
            {
                "step": 3,
                "reasoning": "Check promoted_to_fact in the response to confirm evidence was accepted.",
                "confidence": 0.85,
            },
        ],
    },
    {
        "content": "Pattern 3 (multi-agent shared silo): silo isolation is handled by auth; agents sharing a silo see the same context without passing extra params.",
        "layer": "intelligence",
        "tags": ["api", "mcp", "pattern", "agent-integration", "multi-agent", "tenancy"],
        "evidence": [],
        "about": [],
        "steps": [
            {
                "step": 1,
                "reasoning": "Agent A stores shared context to memory with descriptive tags; silo_id is implicit from auth.",
                "confidence": 0.95,
            },
            {
                "step": 2,
                "reasoning": "Agent B, authenticated to the same silo, calls context_recall search; shared context is visible without extra configuration.",
                "confidence": 0.95,
            },
            {
                "step": 3,
                "reasoning": "No silo_id param is needed in either call; the session token determines the addressed silo.",
                "confidence": 0.98,
            },
        ],
    },
    {
        "content": "Pattern 4 (graph traversal for related context): seed with a semantic query in graph mode with depth=2 to hop the knowledge graph and surface related nodes beyond direct search hits.",
        "layer": "intelligence",
        "tags": ["api", "mcp", "pattern", "agent-integration", "graph"],
        "evidence": [],
        "about": [],
        "steps": [
            {
                "step": 1,
                "reasoning": "Call context_recall with mode=graph, a semantic query string, depth=2, and top_k=30.",
                "confidence": 0.95,
            },
            {
                "step": 2,
                "reasoning": "Inspect traversal_stats to understand depth_reached and nodes_visited.",
                "confidence": 0.85,
            },
            {
                "step": 3,
                "reasoning": "Use the returned nodes and edges to build a local context graph for reasoning.",
                "confidence": 0.9,
            },
        ],
    },
    {
        "content": "Pattern 5 (reasoning chain to intelligence layer): store a multi-step reasoning chain to intelligence layer; the service automatically queues crystallizations as knowledge candidates.",
        "layer": "intelligence",
        "tags": ["api", "mcp", "pattern", "agent-integration", "intelligence"],
        "evidence": [],
        "about": [],
        "steps": [
            {
                "step": 1,
                "reasoning": "Construct a steps list where each entry has step (int), reasoning (str), and optionally confidence (float).",
                "confidence": 0.95,
            },
            {
                "step": 2,
                "reasoning": "Call context_store with layer=intelligence, a summary conclusion as content, and the steps list.",
                "confidence": 0.95,
            },
            {
                "step": 3,
                "reasoning": "Check crystallizations_queued in the response to confirm emergent claims were extracted.",
                "confidence": 0.85,
            },
        ],
    },
    {
        "content": "Pattern 6 (commit belief to wisdom): after accumulating knowledge and reasoning chains, commit a synthesized judgment to wisdom layer with about pointing to supporting node IDs.",
        "layer": "intelligence",
        "tags": ["api", "mcp", "pattern", "agent-integration", "wisdom"],
        "evidence": [],
        "about": [],
        "steps": [
            {
                "step": 1,
                "reasoning": "Collect node IDs of knowledge nodes and intelligence chains that ground the belief.",
                "confidence": 0.95,
            },
            {
                "step": 2,
                "reasoning": "Call context_store with layer=wisdom, the belief as content, and about=[knowledge_node_id, chain_node_id].",
                "confidence": 0.95,
            },
            {
                "step": 3,
                "reasoning": "Verify declared_by in the response matches the agent's identity.",
                "confidence": 0.8,
            },
        ],
    },
    {
        "content": "Pattern 7 (trace provenance then history): use provenance mode to find a claim's Memory-layer sources, then use history mode to see how the claim evolved via the SUPERSEDES chain.",
        "layer": "intelligence",
        "tags": ["api", "mcp", "pattern", "agent-integration", "provenance", "history"],
        "evidence": [],
        "about": [],
        "steps": [
            {
                "step": 1,
                "reasoning": "Call context_recall with mode=provenance and the target node_id to retrieve the citation chain and root_sources.",
                "confidence": 0.95,
            },
            {
                "step": 2,
                "reasoning": "Call context_recall with mode=history and the same node_id to retrieve the SUPERSEDES timeline.",
                "confidence": 0.95,
            },
            {
                "step": 3,
                "reasoning": "Compare root_sources with timeline entries to understand how raw observations became validated facts.",
                "confidence": 0.9,
            },
        ],
    },
]
